baldinof_road_runner:
  kernel_reboot:
    strategy: on_exception
    allowed_exceptions:
      - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
      - Symfony\Component\Serializer\Exception\ExceptionInterface
      - Symfony\Contracts\HttpClient\Exception\ExceptionInterface
  # See https://github.com/baldinof/roadrunner-bundle#metrics
  metrics:
    enabled: false
