snc_redis:
  clients:
    cache:
      alias: cache
      dsn: redis://redis:6379/0
      logging: '%kernel.debug%'
      options:
        connection_persistent: true
      type: predis
    default:
      alias: default
      dsn: redis://redis:6379/1
      logging: '%kernel.debug%'
      options:
        connection_persistent: true
      type: predis
    session:
      alias: session
      dsn: redis://redis:6379/2
      logging: '%kernel.debug%'
      options:
        connection_persistent: true
      type: predis
