version: '2'

services:
  roadrunner:
    build:
      context: ./containers/roadrunner
      args:
        RR_VERSION: ${RR_VERSION}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
    ports:
      - 8080:8080
    environment:
      RR_VERSION: ${RR_VERSION}
    working_dir: /app
    volumes:
      - ./:/app
      - ./containers/roadrunner/config/.rr.yaml:/etc/rr.yaml:ro
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
