services:
  redis:
    image: 'redis:${REDIS_VERSION}-alpine'
    ports:
      - '6379:6379/tcp'
    restart: unless-stopped
    volumes:
      - 'redis-data:/data'
  roadrunner:
    build:
      args:
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
        RR_VERSION: ${RR_VERSION}
      context: ./containers/roadrunner
      target: '${DOCKER_TARGET}'
    environment:
      RR_VERSION: ${RR_VERSION}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${DOCKER_HOST_PORT}:8080/tcp'
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  redis-data:
    driver: local
