services:
  roadrunner:
    build:
      args:
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
        RR_VERSION: ${RR_VERSION}
      context: ./containers/roadrunner
      # target: production
      target: development
    environment:
      RR_VERSION: ${RR_VERSION}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080/tcp'
    working_dir: /app
    volumes:
      - ./:/app
