services:
  roadrunner:
    build:
      args:
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
        RR_VERSION: ${RR_VERSION}
      context: ./containers/roadrunner
      # target: production
      target: development
    environment:
      RR_VERSION: ${RR_VERSION}
    ports:
      - '8080:8080/tcp'
    working_dir: /app
    volumes:
      - ./:/app
      - ./containers/roadrunner/config/.rr.yaml:/etc/rr.yaml:ro
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
