version: "3"

server:
  command: "php /app/public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: :8080
  pool:
    num_workers: 1
    max_jobs: 1
    debug: true
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "/app/public"
    forbid: [ ".php", ".htaccess" ]

# See https://roadrunner.dev/docs/plugins-logger/2.x/en#summary.
logs:
  mode: production
  encoding: json
  channels:
    http:
      level: debug
    server:
      level: info
    metrics:
      level: error

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/app" ]
