parameters:
  .container.dumper.inline_factories: true

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Baldinof\Middleware\PredisMiddleware:
    arguments:
      - !tagged_iterator snc_redis.client

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@snc_redis.session'
